name: Deployment Production Ticketing

on: 
  push:
    branches: dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Connect SSH & Pulling request
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: noretest.com
          username: u1748803
          port: 65002
          privateKey: ${{ secrets.PRIVATE_KEY_TEST }}
          command: |
            cd public_html/optest
            git pull
            composer install
            composer dump-autoload
            php artisan migrate --force
        env:
          CI: true
